// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed clip.png
var resourceClipPngData []byte
var resourceClipPng = &fyne.StaticResource{
	StaticName:    "clip.png",
	StaticContent: resourceClipPngData,
}
